name: flutter_application_e_commerce_app
description: 'A new Flutter project.'
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
    sdk: '>=3.3.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
    flutter:
        sdk: flutter

    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
    cupertino_icons: ^1.0.6
    provider: ^6.1.2
    carousel_slider: ^4.2.1
    rive: ^0.13.1
    intl: ^0.19.0
    firebase_core: ^2.30.1
    firebase_auth: ^4.19.4
    cloud_firestore: ^4.17.2
    add_to_cart_animation: ^2.0.3

dev_dependencies:
    flutter_test:
        sdk: flutter

    # The "flutter_lints" package below contains a set of recommended lints to
    # encourage good coding practices. The lint set provided by the package is
    # activated in the `analysis_options.yaml` file located at the root of your
    # package. See that file for information about deactivating specific lint
    # rules and activating additional ones.
    flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true

    # To add assets to your application, add an assets section, like this:
    assets:
        - assets/img/logo.png
        - assets/img/user_img.png
        - assets/img/logo_2.png
        - assets/img/banner.jpg
        - assets/img/coupon-svgrepo-com.png
        - assets/img/burger.jpg
        - assets/img/hotdog.png
        - assets/img/coca_cola.jpg
        - assets/img/pizza_category.png
        - assets/img/hamburger_category.png
        - assets/img/noodle_category.png
        - assets/img/hotdog_category.png
        - assets/img/drink_category.png
        - assets/img/sandwich_category.png
        - assets/img/pizza_banner.jpg
        - assets/img/burger_banner.jpg
        - assets/img/fastfood_banner.jpg
        - assets/img/pizza.jpg
        - assets/img/pizza_seafood.jpg
        - assets/img/pizza_seafood.jpg
        - assets/img/pizza_beef.jpg
        - assets/img/pizza_cheese.jpg
        - assets/img/pizza_hawaii.jpg
        - assets/img/pizza_margherita.jpg
        - assets/img/pizza_pesto.jpg
        - assets/img/setting-setting-svgrepo-com.png
        - assets/img/order-food-svgrepo-com.png
        - assets/img/favorite-favorite-svgrepo-com.png
        - assets/img/discount-star-svgrepo-com.png
        - assets/img/customer-service-help-svgrepo-com.png
        - assets/img/shopping-basket-shopper-svgrepo-com.png
        - assets/img/search-svgrepo-com.png
        - assets/img/fire-svgrepo-com.png
        - assets/img/information-info-svgrepo-com.png
        - assets/img/placeholder-gps-svgrepo-com.png
        - assets/img/email-mail-svgrepo-com.png
        - assets/img/7up.png
        - assets/img/beef_sandwich.png
        - assets/img/burger_chicken.jpg
        - assets/img/burger_fish.jpg
        - assets/img/burger_sheep.png
        - assets/img/cannelloni_noodle.jpg
        - assets/img/cheese_sandwich.jpg
        - assets/img/chicken_sandwich.jpg
        - assets/img/egg_sandwich.jpg
        - assets/img/hotdog_chocolate.jpg
        - assets/img/hotdog_korea.jpg
        - assets/img/hotdog_rainbow.png
        - assets/img/linguine_noodle.jpg
        - assets/img/monte_cristo_sandwich.jpg
        - assets/img/penne_noodle.jpg
        - assets/img/pepsi.jpg
        - assets/img/spaghetti_noodle.jpg
        - assets/img/sprite.jpg
        - assets/img/sting_blue.jpg
        - assets/img/tuna_sandwich.jpg
        - assets/img/error-svgrepo-com.png
        - assets/img/face-with-tongue-svgrepo-com.png

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
